import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { AppSidebar } from '@/components/app-sidebar';
import Header from '@/components/header';
import { Providers } from '@/components/providers';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';

const fontSans = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark scheme-only-dark">
      <body className={`${fontSans.variable} font-sans antialiased`}>
        <Providers>
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset className="overflow-hidden px-4 md:px-6 lg:px-8">
              <Header />
              {children}
            </SidebarInset>
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}
